[build]
  base = "/docs"
  command = "yarn run build"
  publish = "build"
  environment = { NODE_VERSION = "14" }

# Manually start your application (CRA or other) on port 3000 before
# running `netlify dev` or `yarn dev`.
[dev]
  port = 8888
  command = "yarn workspace use-shopping-cart build:watch"
  targetPort = 3000
  framework = "#custom"
  autoLaunch = true

[[redirects]]
  from = "https://use-shopping-cart.netlify.app"
  to = "https://useshoppingcart.com"
  status = 301
